[package]
name = "reck-core"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "reck-core"
path = "src/main.rs"

[dependencies]
tonic = "0.11"
prost = "0.12"
prost-types = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dashmap = "5.5"
chrono = "0.4"

[build-dependencies]
tonic-build = "0.11"
